export { default as Login } from "./login";
export { default as AdminKamar } from "./admin/kamar";
export { default as AdminTipeKamar } from "./admin/tipe kamar";
export { default as AdminUser } from "./admin/user";
export { default as AdminDashboard } from "./admin/dashboard";
export { default as ResepsionisDashboard } from "./resepsionis/dashboard";
export { default as ResepsionisPemesanan } from "./resepsionis/pemesanan";
export { default as ReseprionisDetailPemesanan } from "./resepsionis/detail pemesanan";
export { default as TamuDashboard } from "./tamu/dashboard";
export { default as TamuKamar } from "./tamu/kamar";
export { default as TamuDetailKamar } from "./tamu/detail kamar";
export { default as TamuCekPemesanan } from "./tamu/cek pemesanan";
export { default as TamuCetakPemesanan } from "./tamu/cek pemesanan/fragments/HalamanCetak";
export { default as TamuPemesanan } from "./tamu/pemesanan";
export { default as TamuHistoriPemesanan } from "./tamu/histori pemesanan";
